name: Bioconda CDN Sync
on:
  workflow_dispatch:
  schedule:
    - cron: "36 * * * *"

jobs:
  Check-Bioconda-Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          # cache: "pip"
      - run: pip install -r requirements.txt
      - id: script
        run: python main.py
      - name: Sync works
        if: ${{ env.result == '0' }}
        run: |
          echo "Sync success"
          echo "${{ env.output }}"
          echo "${{ env.result }}"
          rm sync_out_of_date || true
      - name: Sync out of date
        if: ${{ env.result == '1' }}
        run: |
          echo "Sync not success"
          if [ ! -f sync_out_of_date ]; then
             gh issue create -R bioconda/bioconda-recipes --title "Bioconda CDN sync >2hr behind" --body "${{ env.output }}"
             touch sync_out_of_date
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION }}
      - name: echo result into README
        run: |
          echo "${{ env.output }}" > README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update lock file
